name: build-test
on:
  push:
    branches:
      - $default-branch
      - develop
  pull_request:
    branches:
      - $default-branch
      - develop

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build
        run: |
          ls
          docker build -t supermarket .
