name: test-build-deploy
on:
  push:
    branches:
      - $default-branch
      - develop
  pull_request:
    branches:
      - $default-branch
      - develop

jobs:
  test:
    container:
      image: golang:1.17
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: test
        run: |
          go test -v ./...

  build:
    services:
      buildService:
        image: golang:1.17
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t supermarket:$GITHUB_SHA .

  deploy:
    needs:
      - test
      - build
    if: ${{ github.ref_name == 'main' }}
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          echo "deploy"
