name: test-build-deploy
on:
  push:
    branches:
      - $default-branch
      - develop
  pull_request:
    branches:
      - $default-branch
      - develop

jobs:
  test:
    runs-on: self-hosted
    container:
      image: golang:1.17
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: test
        run: |
          go test -v ./...

  build:
    needs: test
    runs-on: self-hosted
    container:
      image: golang:1.17
      volumes:
        - /usr/bin/docker:/usr/bin/docker
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker build -t supermarket:$GITHUB_SHA .
          docker image tag supermarket:$GITHUB_SHA dsbevan/supermarket:$GITHUB_SHA
          docker image push dsbevan/supermarket:$GITHUB_SHA

  deploy:
    needs:
      - build
    if: ${{ github.ref_name == 'main' }}
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          echo "deploy"
