name: test-build-deploy

on:
  push:
    branches:
      - develop
      - main
    paths:
      - '**.go'
      - '.github/**'
      - 'config.json'
      - 'Dockerfile'
  pull_request:
    branches:
      - develop
      - main
    paths:
      - '**.go'
      - '.github/**'
      - 'config.json'
      - 'Dockerfile'

jobs:
  test:
    runs-on: self-hosted
    container:
      image: golang:1.17
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: test
        run: |
          go test -v ./...

  build:
    needs: test
    runs-on: self-hosted
    container:
      image: golang:1.17
      volumes:
        - /usr/bin/docker:/usr/bin/docker
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker build -t supermarket:$GITHUB_SHA .
      - name: Push develop image
        if: github.ref_name == 'develop'
        env:
          REGISTRY_NAME: dsbevan/supermarket-develop
        run: |
          docker image tag supermarket:$GITHUB_SHA $REGISTRY_NAME:$GITHUB_SHA
          docker image push $REIGSTRY_NAME:$GITHUB_SHA
          docker image tag supermarket:$GITHUB_SHA $REIGSTRY_NAME:latest
          docker image push $REIGSTRY_NAME:latest
      - name: Push production image
        if: github.ref_name == 'main'
        env:
          REGISTRY_NAME: dsbevan/supermarket
        run: |
          docker image tag supermarket:$GITHUB_SHA $REGISTRY_NAME:$GITHUB_SHA
          docker image push $REIGSTRY_NAME:$GITHUB_SHA
          docker image tag supermarket:$GITHUB_SHA $REIGSTRY_NAME:latest
          docker image push $REIGSTRY_NAME:latest

  deploy:
    needs:
      - build
    if: github.ref_name == 'main'
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          echo "deploy"
